---
- name: Provision {{ ec2_server_instcount }} EC2 instances.
  local_action:
    module: ec2
    key_name: "{{ ec2_server_keypair }}"
    aws_access_key: "{{ ec2_server_access_key }}"
    aws_secret_key: "{{ ec2_server_secret_key }}"
    group_id: "{{ ec2_server_security_group }}"
    instance_type: "{{ ec2_server_instance_type }}"
    image: "{{ ec2_server_image }}"
    region: "{{ ec2_server_region }}"
    vpc_subnet_id: "{{ ec2_server_subnet_id }}"
    wait: yes
    count: "{{ ec2_server_instcount }}"
    assign_public_ip: yes
  register: ec2

- name: Display Instance Ids.
  debug: msg="{{ ec2.instance_ids }}"

- name: Wait for SSH.
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ ec2.instances }}"
